# Generated by Django 3.2.6 on 2021-08-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0012_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='clients',
            name='fullname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
