# Generated by Django 3.2.6 on 2021-08-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0013_auto_20210809_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Nationality',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
