# Generated by Django 3.2.6 on 2021-08-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0018_auto_20210811_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
